//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popcorn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Popcorn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actors.
        /// </summary>
        public static string ActorsLabel {
            get {
                return ResourceManager.GetString("ActorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AllLabel {
            get {
                return ResourceManager.GetString("AllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string AverageLabel {
            get {
                return ResourceManager.GetString("AverageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad.
        /// </summary>
        public static string BadLabel {
            get {
                return ResourceManager.GetString("BadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering.
        /// </summary>
        public static string BufferingLabel {
            get {
                return ResourceManager.GetString("BufferingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache size (in MB).
        /// </summary>
        public static string CacheSizeLabel {
            get {
                return ResourceManager.GetString("CacheSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cast media..
        /// </summary>
        public static string CastFailed {
            get {
                return ResourceManager.GetString("CastFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast.
        /// </summary>
        public static string CastLabel {
            get {
                return ResourceManager.GetString("CastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast to.
        /// </summary>
        public static string CastToLabel {
            get {
                return ResourceManager.GetString("CastToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Chromecast.
        /// </summary>
        public static string ChooseChromecastLabel {
            get {
                return ResourceManager.GetString("ChooseChromecastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a subtitle.
        /// </summary>
        public static string ChooseSubtitleLabel {
            get {
                return ResourceManager.GetString("ChooseSubtitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        public static string CollectionsLabel {
            get {
                return ResourceManager.GetString("CollectionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password....
        /// </summary>
        public static string ConfirmPasswordWatermark {
            get {
                return ResourceManager.GetString("ConfirmPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECTING TO CHROMECAST.
        /// </summary>
        public static string ConnectingToChomecastLabel {
            get {
                return ResourceManager.GetString("ConnectingToChomecastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to have an internet connection error. Please retry..
        /// </summary>
        public static string ConnectionErrorDescriptionPopup {
            get {
                return ResourceManager.GetString("ConnectionErrorDescriptionPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection error.
        /// </summary>
        public static string ConnectionErrorTitlePopup {
            get {
                return ResourceManager.GetString("ConnectionErrorTitlePopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently playing.
        /// </summary>
        public static string CurrentlyPlayingLabel {
            get {
                return ResourceManager.GetString("CurrentlyPlayingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string CustomLabel {
            get {
                return ResourceManager.GetString("CustomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default quality.
        /// </summary>
        public static string DefaultQualityLabel {
            get {
                return ResourceManager.GetString("DefaultQualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default subtitle language.
        /// </summary>
        public static string DefaultSubtitleLanguageLabel {
            get {
                return ResourceManager.GetString("DefaultSubtitleLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directors.
        /// </summary>
        public static string DirectorsLabel {
            get {
                return ResourceManager.GetString("DirectorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading subtitles....
        /// </summary>
        public static string DownloadingSubtitlesLabel {
            get {
                return ResourceManager.GetString("DownloadingSubtitlesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadLabel {
            get {
                return ResourceManager.GetString("DownloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download limit (kB/s).
        /// </summary>
        public static string DownloadLimitLabel {
            get {
                return ResourceManager.GetString("DownloadLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email....
        /// </summary>
        public static string EmailWatermark {
            get {
                return ResourceManager.GetString("EmailWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s embarrassing....
        /// </summary>
        public static string EmbarrassingError {
            get {
                return ResourceManager.GetString("EmbarrassingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No movie found.
        /// </summary>
        public static string EmptyMovieSearchLabel {
            get {
                return ResourceManager.GetString("EmptyMovieSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No show found.
        /// </summary>
        public static string EmptyShowSearchLabel {
            get {
                return ResourceManager.GetString("EmptyShowSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episodes.
        /// </summary>
        public static string EpisodesLabel {
            get {
                return ResourceManager.GetString("EpisodesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A critical error has occured. You should restart the app immediately..
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string FavoritesTitleTab {
            get {
                return ResourceManager.GetString("FavoritesTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name....
        /// </summary>
        public static string FirstNameWatermark {
            get {
                return ResourceManager.GetString("FirstNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string GenresLabel {
            get {
                return ResourceManager.GetString("GenresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string GoodLabel {
            get {
                return ResourceManager.GetString("GoodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greatest.
        /// </summary>
        public static string GreatestTitleTab {
            get {
                return ResourceManager.GetString("GreatestTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string HealthLabel {
            get {
                return ResourceManager.GetString("HealthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpLabel {
            get {
                return ResourceManager.GetString("HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name....
        /// </summary>
        public static string LastNameWatermark {
            get {
                return ResourceManager.GetString("LastNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string LaterLabel {
            get {
                return ResourceManager.GetString("LaterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string LicenseLabel {
            get {
                return ResourceManager.GetString("LicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCOVERING CHROMECASTS....
        /// </summary>
        public static string LoadingChromecastsLabel {
            get {
                return ResourceManager.GetString("LoadingChromecastsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading trailer....
        /// </summary>
        public static string LoadingTrailerLabel {
            get {
                return ResourceManager.GetString("LoadingTrailerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string MovieQualityLabel {
            get {
                return ResourceManager.GetString("MovieQualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MovieSettingsLabel {
            get {
                return ResourceManager.GetString("MovieSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string MoviesLabel {
            get {
                return ResourceManager.GetString("MoviesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movies.
        /// </summary>
        public static string MoviesWord {
            get {
                return ResourceManager.GetString("MoviesWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new update has been applied. Would you like to restart now?.
        /// </summary>
        public static string NewUpdateDescriptionLabel {
            get {
                return ResourceManager.GetString("NewUpdateDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update.
        /// </summary>
        public static string NewUpdateLabel {
            get {
                return ResourceManager.GetString("NewUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO CHROMECAST AVAILABLE.
        /// </summary>
        public static string NoChromecastLabel {
            get {
                return ResourceManager.GetString("NoChromecastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no media file in the torrent you dropped in the UI..
        /// </summary>
        public static string NoMediaInDroppedTorrent {
            get {
                return ResourceManager.GetString("NoMediaInDroppedTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no media file in the torrent..
        /// </summary>
        public static string NoMediaInTorrent {
            get {
                return ResourceManager.GetString("NoMediaInTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NoneLabel {
            get {
                return ResourceManager.GetString("NoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No similar movie found.
        /// </summary>
        public static string NoSimilarLabel {
            get {
                return ResourceManager.GetString("NoSimilarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string NowLabel {
            get {
                return ResourceManager.GetString("NowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OffLabel {
            get {
                return ResourceManager.GetString("OffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string OfWord {
            get {
                return ResourceManager.GetString("OfWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OnLabel {
            get {
                return ResourceManager.GetString("OnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password....
        /// </summary>
        public static string PasswordWatermark {
            get {
                return ResourceManager.GetString("PasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peers.
        /// </summary>
        public static string PeersLabel {
            get {
                return ResourceManager.GetString("PeersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string PlayingTitleTab {
            get {
                return ResourceManager.GetString("PlayingTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PlayLabel {
            get {
                return ResourceManager.GetString("PlayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string PopularShowTitleTab {
            get {
                return ResourceManager.GetString("PopularShowTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular.
        /// </summary>
        public static string PopularTitleTab {
            get {
                return ResourceManager.GetString("PopularTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string RatingLabel {
            get {
                return ResourceManager.GetString("RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string RecentTitleTab {
            get {
                return ResourceManager.GetString("RecentTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string ReloadLabel {
            get {
                return ResourceManager.GetString("ReloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchBoxWatermark {
            get {
                return ResourceManager.GetString("SearchBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchTitleTab {
            get {
                return ResourceManager.GetString("SearchTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeders.
        /// </summary>
        public static string SeedersLabel {
            get {
                return ResourceManager.GetString("SeedersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seen.
        /// </summary>
        public static string SeenTitleTab {
            get {
                return ResourceManager.GetString("SeenTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenuTitle {
            get {
                return ResourceManager.GetString("SettingsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows.
        /// </summary>
        public static string ShowsLabel {
            get {
                return ResourceManager.GetString("ShowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shows.
        /// </summary>
        public static string ShowsWord {
            get {
                return ResourceManager.GetString("ShowsWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar.
        /// </summary>
        public static string SimilarLabel {
            get {
                return ResourceManager.GetString("SimilarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (kB/s).
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopLabel {
            get {
                return ResourceManager.GetString("StopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles color.
        /// </summary>
        public static string SubtitlesColorLabel {
            get {
                return ResourceManager.GetString("SubtitlesColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitles.
        /// </summary>
        public static string SubtitlesLabel {
            get {
                return ResourceManager.GetString("SubtitlesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer.
        /// </summary>
        public static string TrailerButton {
            get {
                return ResourceManager.GetString("TrailerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trailer is not available for the current language..
        /// </summary>
        public static string TrailerNotAvailable {
            get {
                return ResourceManager.GetString("TrailerNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownLabel {
            get {
                return ResourceManager.GetString("UnknownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release informations:.
        /// </summary>
        public static string UpdateReleasesInformationsLabel {
            get {
                return ResourceManager.GetString("UpdateReleasesInformationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadLabel {
            get {
                return ResourceManager.GetString("UploadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload limit (kB/s).
        /// </summary>
        public static string UploadLimitLabel {
            get {
                return ResourceManager.GetString("UploadLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username....
        /// </summary>
        public static string UsernameWatermark {
            get {
                return ResourceManager.GetString("UsernameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version history.
        /// </summary>
        public static string VersionHistoryLabel {
            get {
                return ResourceManager.GetString("VersionHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very bad.
        /// </summary>
        public static string VeryBadLabel {
            get {
                return ResourceManager.GetString("VeryBadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very good.
        /// </summary>
        public static string VeryGoodLabel {
            get {
                return ResourceManager.GetString("VeryGoodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        public static string WatchButton {
            get {
                return ResourceManager.GetString("WatchButton", resourceCulture);
            }
        }
    }
}
